# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-agency
remote_theme: applygrad/agency-jekyll-theme

url    : "https://applygrad.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : Illume Education
email      : zeyongj@gmail.com #this is also the email contact forms will go to
description: "Ask us for graduate schools selection, application, and more!"
author     : Yunqi
# logo:     #optional, defaults to site title
#   path: assets\img\clients\creative-market.jpg
#   height: 60 #height in px, defaults to 52px

locale: "zh-CN" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "f/xdornjrd" # f/mnqkaoao

plugins:
  - jekyll-remote-theme

# <form id="fs-frm" name="complaint-form" accept-charset="utf-8" action="https://formspree.io/f/{form_id}" method="post">
#   <fieldset id="fs-frm-inputs">
#     <label for="full-name">姓名</label>
#     <input type="text" name="name" id="full-name" placeholder="请输入姓名" required="">
#     <label for="email-address">电子邮件地址</label>
#     <input type="email" name="_replyto" id="email-address" placeholder="email@domain.tld" required="">
#     <label for="telephone">联系电话（选填）</label>
#     <input type="telephone" name="telephone" id="telephone" placeholder="(555) 555-5555">
#     <label for="complaint">毕业院校、GPA、申研诉求</label>
#     <textarea rows="6" name="complaint" id="complaint" placeholder="请告诉我们您的毕业院校，成绩，以及希望申请的学校项目等。" required=""></textarea>
#     <input type="hidden" name="_subject" id="email-subject" value="Complaint Form Submission">
#   </fieldset>
#   <input type="submit" value="提交">
# </form><style>/* reset */
# #fs-frm input,
# #fs-frm select,
# #fs-frm textarea,
# #fs-frm fieldset,
# #fs-frm optgroup,
# #fs-frm label,
# #fs-frm #card-element:disabled {
#   font-family: inherit;
#   font-size: 100%;
#   color: inherit;
#   border: none;
#   border-radius: 0;
#   display: block;
#   width: 100%;
#   padding: 0;
#   margin: 0;
#   -webkit-appearance: none;
#   -moz-appearance: none;
# }
# #fs-frm label,
# #fs-frm legend,
# #fs-frm ::placeholder {
#   font-size: .825rem;
#   margin-bottom: .5rem;
#   padding-top: .2rem;
#   display: flex;
#   align-items: baseline;
# }

# /* border, padding, margin, width */
# #fs-frm input,
# #fs-frm select,
# #fs-frm textarea,
# #fs-frm #card-element {
#   border: 1px solid rgba(0,0,0,0.2);
#   background-color: rgba(255,255,255,0.9);
#   padding: .75em 1rem;
#   margin-bottom: 1.5rem;
# }
# #fs-frm input:focus,
# #fs-frm select:focus,
# #fs-frm textarea:focus {
#   background-color: white;
#   outline-style: solid;
#   outline-width: thin;
#   outline-color: gray;
#   outline-offset: -1px;
# }
# #fs-frm [type="text"],
# #fs-frm [type="email"] {
#   width: 100%;
# }
# #fs-frm [type="button"],
# #fs-frm [type="submit"],
# #fs-frm [type="reset"] {
#   width: auto;
#   cursor: pointer;
#   -webkit-appearance: button;
#   -moz-appearance: button;
#   appearance: button;
# }
# #fs-frm [type="button"]:focus,
# #fs-frm [type="submit"]:focus,
# #fs-frm [type="reset"]:focus {
#   outline: none;
# }
# #fs-frm [type="submit"],
# #fs-frm [type="reset"] {
#   margin-bottom: 0;
# }
# #fs-frm select {
#   text-transform: none;
# }

# #fs-frm [type="checkbox"] {
#   -webkit-appearance: checkbox;
#   -moz-appearance: checkbox;
#   appearance: checkbox;
#   display: inline-block;
#   width: auto;
#   margin: 0 .5em 0 0 !important;
# }

# #fs-frm [type="radio"] {
#   -webkit-appearance: radio;
#   -moz-appearance: radio;
#   appearance: radio;
# }

# /* address, locale */
# #fs-frm fieldset.locale input[name="city"],
# #fs-frm fieldset.locale select[name="state"],
# #fs-frm fieldset.locale input[name="postal-code"] {
#   display: inline;
# }
# #fs-frm fieldset.locale input[name="city"] {
#   width: 52%;
# }
# #fs-frm fieldset.locale select[name="state"],
# #fs-frm fieldset.locale input[name="postal-code"] {
#   width: 20%;
# }
# #fs-frm fieldset.locale input[name="city"],
# #fs-frm fieldset.locale select[name="state"] {
#   margin-right: 3%;
# }
# </style>
